const $=s=>document.querySelector(s);const view=$('#view');
const places=['All','Victoria Falls','Chobe','Khwai','Okavango'];const groups=['All','mammal','bird','reptile'];
let route=location.hash.slice(1)||'home', place='All', group='All', query='';
const seen=()=>JSON.parse(localStorage.getItem('safariSeen')||'{}');
function saveSeen(o){localStorage.setItem('safariSeen',JSON.stringify(o));}
function esc(s){return String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function key(s){return 'photo-'+s.id}
async function wikiImage(s){const cached=localStorage.getItem(key(s));if(cached)return JSON.parse(cached);try{const u='https://en.wikipedia.org/api/rest_v1/page/summary/'+encodeURIComponent(s.name.replace(/’/g,"'"));const r=await fetch(u);if(!r.ok)throw 0;const d=await r.json();const out={url:d.thumbnail?.source||d.originalimage?.source||'',article:d.content_urls?.desktop?.page||'',title:d.title||s.name};localStorage.setItem(key(s),JSON.stringify(out));return out}catch(e){return {url:'',article:'',title:s.name}}}
function img(s){const c=localStorage.getItem(key(s));let src='';try{src=c?JSON.parse(c).url:''}catch{}return src||'data:image/svg+xml;charset=UTF-8,'+encodeURIComponent(`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 800 500"><rect width="800" height="500" fill="#d9d5c8"/><text x="400" y="240" text-anchor="middle" font-size="38" fill="#5b625b">${s.name}</text><text x="400" y="290" text-anchor="middle" font-size="20" fill="#777">Photo loads when online</text></svg>`)}
function card(s){const v=seen()[s.id];return `<article class="species-card" data-id="${s.id}"><img loading="lazy" src="${img(s)}" alt="${esc(s.name)}"><div class="species-body"><button class="seen ${v?'yes':''}" data-seen="${s.id}">${v?'✓ Seen':'○'}</button><h3>${esc(s.name)}</h3><div class="muted"><i>${esc(s.scientific)}</i></div><span class="badge">${esc(s.likelihood)}</span></div></article>`}
function filtered(){return SPECIES.filter(s=>(place==='All'||s.places.includes(place))&&(group==='All'||s.group===group)&&(!query||[s.name,s.scientific,s.desc,s.pattern,s.feature].join(' ').toLowerCase().includes(query.toLowerCase())))}
function home(){const total=SPECIES.length, done=Object.keys(seen()).length;view.innerHTML=`<section class="hero"><h2>Your southern African field guide</h2><p>Designed for Victoria Falls, Chobe National Park, Khwai and the Okavango Delta. Browse species, identify unfamiliar animals and keep a local sighting list.</p><div class="progress"><div style="width:${Math.min(100,done/total*100)}%"></div></div><p class="muted">${done} of ${total} species marked seen.</p><div class="row"><button class="bigbtn" data-route="identify">Identify something</button><button class="bigbtn secondary" data-route="browse">Browse species</button></div></section><div class="grid"><div class="card"><h3>🐘 Mammals</h3><p class="muted">${SPECIES.filter(s=>s.group==='mammal').length} species</p></div><div class="card"><h3>🦅 Birds</h3><p class="muted">${SPECIES.filter(s=>s.group==='bird').length} species</p></div><div class="card"><h3>🐊 Reptiles</h3><p class="muted">${SPECIES.filter(s=>s.group==='reptile').length} species</p></div><div class="card"><h3>📴 Offline</h3><p class="muted">Prepare photos while online, then use without internet.</p></div></div>`}
function browse(){view.innerHTML=`<input id="search" class="search" placeholder="Search species, field marks or scientific name" value="${esc(query)}"><div class="chips">${places.map(p=>`<button class="chip ${p===place?'active':''}" data-place="${esc(p)}">${esc(p)}</button>`).join('')}</div><div class="chips">${groups.map(g=>`<button class="chip ${g===group?'active':''}" data-group="${g}">${g[0].toUpperCase()+g.slice(1)}</button>`).join('')}</div><div class="species-grid" id="speciesGrid">${filtered().map(card).join('')}</div>`;loadVisible()}
function detail(id){const s=SPECIES.find(x=>x.id==id);if(!s)return;const meta=(()=>{try{return JSON.parse(localStorage.getItem(key(s))||'{}')}catch{return {}}})();view.innerHTML=`<button class="back" data-route="browse">← Back to species</button><article class="detail"><img id="detailImg" src="${img(s)}" alt="${esc(s.name)}"><div class="detail-body"><button class="seen ${seen()[s.id]?'yes':''}" data-seen="${s.id}">${seen()[s.id]?'✓ Seen':'○ Mark seen'}</button><h2>${esc(s.name)}</h2><p class="muted"><i>${esc(s.scientific)}</i></p><p>${esc(s.desc)}</p><div class="chips">${s.places.map(x=>`<span class="chip">${esc(x)}</span>`).join('')}</div><p><b>Size:</b> ${s.size} &nbsp; <b>Diet:</b> ${s.diet}</p><p><b>Field clue:</b> ${s.pattern}; ${s.feature==='none'?'no obvious horns/tusks':s.feature}.</p><div class="row"><button class="bigbtn" data-seen="${s.id}">${seen()[s.id]?'Unmark seen':'Mark as seen'}</button><button class="bigbtn secondary" data-route="identify">Try identification</button></div>${meta.article?`<div class="credit">Photo/source: Wikimedia/Wikipedia-derived image. <a href="${meta.article}" target="_blank" rel="noopener">source</a></div>`:'<div class="credit">Photo is fetched from Wikimedia/Wikipedia when online and cached locally for offline use.</div>'}</div></article>`}
function safari(){const ss=seen();const done=SPECIES.filter(s=>ss[s.id]);view.innerHTML=`<section class="hero"><h2>My Safari</h2><p>${done.length} species recorded out of ${SPECIES.length}.</p><div class="progress"><div style="width:${done.length/SPECIES.length*100}%"></div></div></section>${done.length?`<div class="species-grid">${done.map(card).join('')}</div>`:'<div class="empty">Nothing marked seen yet. Start exploring.</div>'}`}
let step=0, answers={};
function identify(){const qs=[{q:'What kind of animal?',o:[['mammal','Mammal'],['bird','Bird'],['reptile','Reptile']]},{q:'What size is it?',o:[['tiny','Tiny'],['small','Small'],['medium','Medium'],['large','Large'],['very large','Very large']]},{q:'What is the main pattern/colour?',o:[['grey','Grey'],['dark','Dark'],['tawny','Tawny'],['brown','Brown'],['reddish','Reddish'],['white','White'],['blackwhite','Black & white'],['spotted','Spotted'],['striped','Striped'],['patched','Patched'],['blue','Blue/green'],['green','Green'],['orange','Orange'],['patterned','Patterned']]},{q:'Any obvious feature?',o:[['none','None / not obvious'],['horns','Horns'],['tusks','Tusks']] }];const q=qs[step];let candidates=SPECIES.filter(s=>(answers.group? s.group===answers.group:true)&&(answers.size? s.size===answers.size:true)&&(answers.pattern? s.pattern===answers.pattern:true)&&(answers.feature? s.feature===answers.feature:true));if(step>=qs.length){view.innerHTML=`<section class="hero"><h2>Possible matches</h2><p class="muted">Based on your answers. Tap a species for a closer look.</p></section><div class="species-grid">${candidates.slice(0,20).map(card).join('')}</div>${!candidates.length?'<div class="empty">No exact match. Try starting again with broader choices.</div>':''}<button class="bigbtn" data-ident-reset="1">Start again</button>`;loadVisible();return}view.innerHTML=`<section class="hero"><h2>Identify wildlife</h2><p>Step ${step+1} of ${qs.length}</p></section><section class="question"><h3>${q.q}</h3>${q.o.map(([v,t])=>`<button class="option" data-answer="${v}">${t}</button>`).join('')}</section>${candidates.length?`<p class="muted">${candidates.length} possible species remain.</p>`:''}`}
function loadVisible(){document.querySelectorAll('img').forEach(im=>{if(im.dataset.loaded)return;im.dataset.loaded='1';const s=SPECIES.find(x=>x.id==im.closest('[data-id]')?.dataset.id);if(!s)return;wikiImage(s).then(m=>{if(m.url)im.src=m.url})})}
async function prepareOffline(){if(!navigator.onLine){alert('Connect to the internet first, then prepare offline.');return}$('#offlineBtn').textContent='Preparing…';let n=0;for(const s of SPECIES){const m=await wikiImage(s);if(m.url)n++;$('#status').textContent=`Caching photos ${n}/${SPECIES.length}`;}if('serviceWorker' in navigator) await navigator.serviceWorker.ready;localStorage.setItem('offlinePrepared','1');$('#offlineBtn').textContent='Offline ready';$('#status').textContent='Offline ready';alert(`Done. Cached ${n} wildlife photos. You can now test the guide in Airplane Mode.`)}
function render(){if(route==='home')home();else if(route==='browse')browse();else if(route==='safari')safari();else if(route==='identify')identify();else if(route.startsWith('species-'))detail(route.split('-')[1]);loadVisible();}
document.addEventListener('click',e=>{const r=e.target.closest('[data-route]');if(r){route=r.dataset.route;location.hash=route;render();return}const sp=e.target.closest('[data-id]');if(sp&&!e.target.closest('[data-seen]')){route='species-'+sp.dataset.id;location.hash=route;render();return}const sv=e.target.closest('[data-seen]');if(sv){const o=seen(),id=sv.dataset.seen;o[id]=!o[id];if(!o[id])delete o[id];saveSeen(o);render();return}const p=e.target.closest('[data-place]');if(p){place=p.dataset.place;render();return}const g=e.target.closest('[data-group]');if(g){group=g.dataset.group;render();return}const a=e.target.closest('[data-answer]');if(a){answers[['group','size','pattern','feature'][step]]=a.dataset.answer;step++;identify();return}if(e.target.closest('[data-ident-reset]')){step=0;answers={};identify()}});
document.addEventListener('input',e=>{if(e.target.id==='search'){query=e.target.value;document.querySelector('#speciesGrid').innerHTML=filtered().map(card).join('');loadVisible()}});window.addEventListener('hashchange',()=>{route=location.hash.slice(1)||'home';render()});$('#offlineBtn').onclick=prepareOffline;
if('serviceWorker' in navigator)navigator.serviceWorker.register('service-worker.js').catch(()=>{});$('#status').textContent=navigator.onLine?'Online':(localStorage.getItem('offlinePrepared')?'Offline ready':'Offline');render();
